export const component_names = [
    "Navbar",
    "Footer",
    "NavMenu",
    "MinButtons",
    "Card",
    "CardList",
    "CardItem",
    "Input",
    "Button",
    "Table",
    "TableHead",
    "TableBody",
    "TableRow",
    "TableCell",
    "TableDataCell",
    "Button",
    "Table",
    "TableHead",
    "TableBody",
    "TableRow",
    "TableCell",
    "TableDataCell",
] 



export const SidebarData = [
    "Input",
    "Button",
    "Button Group",
    "Checkbox",
    "Floating Action Button",
    "Radio Group",
    "Rating",
    "Select",
    "Slider",
    "Switch",
    "Text Field",
    "Transfer List",
    "Toggle Button",
    "DATA DISPLAY",
    "Avatar",
    "Badge",
    "Chip",
    "Divider",
    "Icons",
    "Material Icons",
    "List",
    "Table",
    "Tooltip",
    "Typography",
    "FEEDBACK",
    "Alert",
    "Backdrop",
    "Dialog",
    "Progress",
    "Skeleton",
    "Snackbar",
    "SURFACES",
    "Accordion",
    "App Bar",
    "Card",
    "Paper",
    "NAVIGATION",
    "Bottom Navigation",
    "Breadcrumbs",
    "Drawer",
    "Link",
    "Menu",
    "Pagination",
    "Speed Dial",
    "Stepper",
    "Tabs",
    "LAYOUT",
    "Box",
    "Container",
    "Grid",
    "Grid v2",
    "NEW",
    "Stack",
    "Image List",
    "Hidden",
]
