import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { ReactNode } from "react";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "ComponentMaster",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex flex-col gap-10">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
